### ISSUE TITLE
error in LDW species legend

### ISSUE THREAD

**Issue by teixeirak** [EcoClimLab/ForestGEO-tree-rings#139]
@ValentineHerr ,

The LDW legend in the figures includes these oak species:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/6355854/127743987-5cba8cd2-5e92-469d-a7a8-2cd04442f8d9.png">

But the analysis includes these:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/6355854/127744007-019cb9b9-0c86-4c3a-b3d7-d01a8092ed64.png">

**Comment by ValentineHerr** [comment]
Good catch @teixeirak... I had the wrong set of species in the legends (only the ones with DBH instead of the ones analyzed - and QUAL has do DBHs so it wasn't showing up. And QURU has DBH but not enough data so it is not analyzed).

I updated the figures. That fixed LDW and also reduced the legend of HF (to only the species analyzed) but otherwise I think everything is the same.

Let me know if that works with you.

**Comment by teixeirak** [comment]
Thanks @ValentineHerr ; looks great!
